# Generated by Django 4.1.3 on 2022-11-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='outcome',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='outcome',
            field=models.IntegerField(null=True),
        ),
    ]
