# Generated by Django 4.1.3 on 2022-11-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_actions_income_alter_actions_outcome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='money',
            new_name='balance',
        ),
    ]
