# Generated by Django 4.1.3 on 2022-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_money_player_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='income',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='business',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='income',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='player',
            name='commant_share',
        ),
        migrations.AddField(
            model_name='actions',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='default',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='payments',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=60000),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
