# Generated by Django 4.1.3 on 2022-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playersbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersbusiness',
            name='status',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
