# Generated by Django 4.1.3 on 2022-11-15 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playersbusiness_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBusinessPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalBusinessPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('defoult', models.IntegerField(default=0)),
                ('level', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='command',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='playersbusiness',
            name='command',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='playersbusiness',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='personalbusinesspayments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playersbusiness'),
        ),
    ]
