# Generated by Django 4.1.3 on 2022-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_commandbusinesspayments_personalbusinesspayments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playersbusiness',
            name='command',
            field=models.BooleanField(default=False),
        ),
    ]
