# Generated by Django 4.1.3 on 2022-11-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_value_actions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='balance',
        ),
        migrations.AlterField(
            model_name='actions',
            name='command',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playersbusiness',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
