# Generated by Django 4.1.3 on 2022-11-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_player_balance_alter_actions_command_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandbusinesspayments',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
