# Generated by Django 4.0.3 on 2022-12-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_command_actions_is_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surprises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PERSONAL', 'personal'), ('COMMAND', 'command'), ('HORECA', 'horeca'), ('REALTY', 'realty'), ('SCIENCE', 'science'), ('IT', 'IT')], default='PERSONAL', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('is_command', models.BooleanField(default=False)),
            ],
        ),
    ]
