# Generated by Django 4.0.3 on 2022-12-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_surprises'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersbusiness',
            name='category',
            field=models.CharField(choices=[('HORECA', 'horeca'), ('REALTY', 'realty'), ('SCIENCE', 'science'), ('IT', 'IT')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surprises',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
