# Generated by Django 4.0.3 on 2022-12-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_playersbusiness_category_alter_surprises_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersbusiness',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('HORECA', 'horeca'), ('REALTY', 'realty'), ('SCIENCE', 'science'), ('IT', 'IT')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
