# Generated by Django 4.0.3 on 2022-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_surprises_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='category',
            field=models.CharField(choices=[('SLR', 'salary'), ('CMND', 'command'), ('BSNS', 'business'), ('SURP', 'surprise'), ('INFL', 'inflation'), ('OTHER', 'other')], default='OTHER', max_length=6),
        ),
    ]
