# Generated by Django 4.0.3 on 2022-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_playersbusiness_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersbusiness',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DEFOULT', 'Defoult')], default='ACTIVE', max_length=10),
        ),
    ]
