# Generated by Django 4.1.3 on 2023-04-25 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_playersbusiness_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=10)),
                ('session_code', models.IntegerField(default=1234)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=8),
        ),
    ]
