# Generated by Django 4.1.3 on 2023-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_gamesessions_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessions',
            name='session_name',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
