# Generated by Django 4.1.3 on 2023-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_gamesessions_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessions',
            name='session_name',
            field=models.CharField(max_length=100),
        ),
    ]
