# Generated by Django 4.1.3 on 2023-04-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_gamesessions_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.gamesessions'),
        ),
    ]
