# Generated by Django 4.1.3 on 2023-04-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_actions_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspayments',
            name='game_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.gamesessions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandpayments',
            name='game_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.gamesessions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playersbusiness',
            name='game_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='game.gamesessions'),
            preserve_default=False,
        ),
    ]
