# Generated by Django 4.1.3 on 2023-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_businesspayments_game_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessions',
            name='session_hash',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
