# Generated by Django 4.1.3 on 2023-05-04 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_gamesessions_session_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='game_session',
        ),
        migrations.AlterField(
            model_name='gamesessions',
            name='session_hash',
            field=models.CharField(default='generated', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesessions')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='move',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.moves'),
        ),
    ]
