# Generated by Django 4.1.3 on 2023-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_actions_game_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moves',
            name='game_session',
        ),
        migrations.AlterField(
            model_name='moves',
            name='number',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
