# Generated by Django 4.1.3 on 2023-05-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_remove_actions_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandpayments',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='commandpayments',
            name='player',
        ),
        migrations.AddField(
            model_name='commandpayments',
            name='move',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.moves'),
        ),
    ]
