# Generated by Django 4.1.3 on 2023-05-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_remove_commandpayments_game_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersbusiness',
            name='game_session',
        ),
    ]
