# Generated by Django 4.1.3 on 2023-05-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_remove_playersbusiness_game_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspayments',
            name='game_session',
        ),
        migrations.AddField(
            model_name='businesspayments',
            name='move',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.moves'),
        ),
    ]
