# Generated by Django 4.1.3 on 2023-05-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_remove_businesspayments_game_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspayments',
            name='player_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playersbusiness'),
        ),
    ]
