# Generated by Django 4.1.3 on 2023-05-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_alter_businesspayments_player_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
