# Generated by Django 4.1.3 on 2023-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_moves_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandpayments',
            name='category',
            field=models.CharField(choices=[('SURP', 'command_surprise'), ('SELL_BIS', 'sell_business'), ('BUY_BIS', 'buy_business'), ('OTHER', 'other')], default='OTHER', max_length=8),
        ),
        migrations.AlterField(
            model_name='actions',
            name='category',
            field=models.CharField(choices=[('SLR', 'salary'), ('CMND', 'command'), ('BSNS', 'business'), ('SURP', 'surprise'), ('INFL', 'inflation'), ('NLWL', 'new_level'), ('OTHER', 'other')], default='OTHER', max_length=6),
        ),
        migrations.AlterField(
            model_name='moves',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
