# Generated by Django 4.1.3 on 2023-05-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_commandpayments_category_alter_actions_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandpayments',
            name='category',
            field=models.CharField(choices=[('SURP', 'command_surprise'), ('SELL_BIS', 'sell_business'), ('DEPOSITE', 'deposite'), ('WITHDRAW', 'withdraw_deposite'), ('BUY_BIS', 'buy_business'), ('OTHER', 'other')], default='OTHER', max_length=8),
        ),
    ]
