# Generated by Django 4.1.3 on 2023-05-10 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_alter_actions_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersbusiness',
            name='status',
        ),
        migrations.AlterField(
            model_name='actions',
            name='category',
            field=models.CharField(choices=[('SLR', 'salary'), ('CMND', 'command'), ('BSNS', 'business'), ('BUY_BIS', 'buy_business'), ('SELL_BIS', 'sell_business'), ('DEF_BIS', 'defoult_business'), ('SURP', 'surprise'), ('INFL', 'inflation'), ('NLWL', 'new_level'), ('OTHER', 'other')], default='OTHER', max_length=9),
        ),
        migrations.CreateModel(
            name='PlayersBusinessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DEFOULT', 'Defoult')], default='ACTIVE', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.moves')),
                ('players_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playersbusiness')),
            ],
        ),
    ]
